# Generated by Django 4.1.4 on 2023-01-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_antihero',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_hero',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_team',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_villian',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
