# Generated by Django 4.1.4 on 2023-01-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_superherobiography_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superheroimages',
            name='small',
            field=models.ImageField(upload_to='images'),
        ),
    ]
