# Generated by Django 4.1.4 on 2023-01-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_alter_superheroimages_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superheroimages',
            name='medium',
            field=models.ImageField(upload_to='images'),
        ),
    ]
